In [115]:
import yfinance as yf
import numpy as np

# Pegando dados e dividindo entre feature e target

In [12]:
# Definir os ativos e o perÃ­odo
ativos4 = ['SUZB3.SA', 'EMBR3.SA', 'PETR4.SA', 'EGIE3.SA', 'BBSE3.SA', 'ITSA4.SA', 'ABEV3.SA', 'WEGE3.SA', 'FLRY3.SA', 'TAEE4.SA', 'USDBRL=X','^BVSP']
data_inicial = '2017-01-01'
data_final = '2024-12-30'

# Obtendo os dados diretamente com o yfinance
tabela_cotacoes = yf.download(ativos4, start=data_inicial, end=data_final)

# Removendo os NA
cotacao_sem_nulos = tabela_cotacoes.dropna()

cotacao_sem_nulos.head()

[*********************100%***********************]  12 of 12 completed

Price           Close                                                        \
Ticker       ABEV3.SA   BBSE3.SA   EGIE3.SA   EMBR3.SA   FLRY3.SA  ITSA4.SA
Date
2017-05-10  14.118645  16.562653  15.847735  15.486094  20.420807  4.513855
2017-05-11  14.368788  16.589911  15.732326  15.545165  20.508598  4.589832
2017-05-12  14.486506  16.987892  15.893902  15.564855  20.578836  4.603240
2017-05-15  14.523292  16.900669  16.009306  15.722375  20.498064  4.603240
2017-05-16  14.582152  17.249584  16.097017  15.545165  20.469973  4.589832

Price                                               ...     Volume             \
Ticker      PETR4.SA   SUZB3.SA  TAEE4.SA USDBRL=X  ...   EGIE3.SA   EMBR3.SA
Date                                                ...
2017-05-10  4.374014  17.149136  5.970147   3.1868  ...  1278375.0  3023300.0
2017-05-11  4.400739  17.149136  5.970147   3.1657  ...   933125.0  1851600.0
2017-05-12  4.587815  17.149136  5.970147   3.1390  ...  1151875.0  2602800.0
2017-05-15  4.656112  17.149136  5.970147   3.1777  ...   778750.0  1710000.0
2017-05-16  4.662052  17.149136  5.970147   3.1082  ...  1115875.0  3023700.0

Price                                                                     \
Ticker       FLRY3.SA    ITSA4.SA    PETR4.SA SUZB3.SA TAEE4.SA USDBRL=X
Date
2017-05-10  1165232.0  21112275.0  46271700.0      0.0    200.0      0.0
2017-05-11  1712429.0  18646839.0  29318000.0      0.0      0.0      0.0
2017-05-12   977743.0  17485227.0  83518200.0      0.0      0.0      0.0
2017-05-15  1654528.0  19569320.0  46914700.0      0.0      0.0      0.0
2017-05-16  1601081.0  37032042.0  34469300.0      0.0      0.0      0.0

Price
Ticker       WEGE3.SA      ^BVSP
Date
2017-05-10  5832060.0  3174100.0
2017-05-11  3423160.0  2872600.0
2017-05-12  5294640.0  3822600.0
2017-05-15  4286100.0  3290300.0
2017-05-16  7818980.0  3672400.0

[5 rows x 60 columns]

In [13]:
cotacao_feature = cotacao_sem_nulos  # Features
cotacao_target = cotacao_sem_nulos['Close']  # Target

In [15]:
cotacao_target.head()

Ticker,ABEV3.SA,BBSE3.SA,EGIE3.SA,EMBR3.SA,FLRY3.SA,ITSA4.SA,PETR4.SA,SUZB3.SA,TAEE4.SA,USDBRL=X,WEGE3.SA,^BVSP
Date,,,,,,,,,,,,
2017-05-10,14.118645,16.562653,15.847735,15.486094,20.420807,4.513855,4.374014,17.149136,5.970147,3.1868,6.620127,67350.0
2017-05-11,14.368788,16.589911,15.732326,15.545165,20.508598,4.589832,4.400739,17.149136,5.970147,3.1657,6.736629,67538.0
2017-05-12,14.486506,16.987892,15.893902,15.564855,20.578836,4.603240,4.587815,17.149136,5.970147,3.1390,6.859986,68222.0
2017-05-15,14.523292,16.900669,16.009306,15.722375,20.498064,4.603240,4.656112,17.149136,5.970147,3.1777,6.997049,68474.0
2017-05-16,14.582152,17.249584,16.097017,15.545165,20.469973,4.589832,4.662052,17.149136,5.970147,3.1082,6.681805,68684.0

# Agrupando features em 10 dias

In [79]:
# Defina o tamanho da janela
window_size = 10

# Crie as janelas 
#cotacao_feature_grouped = [cotacao_feature.iloc[i:i + window_size] for i in range(0, len(cotacao_feature) - window_size)]
cotacao_feature_grouped = [cotacao_feature.iloc[i:i + window_size] for i in range(0, len(cotacao_feature), window_size)]

# Verifique o nÃºmero de janelas criadas e o tamanho das janelas
print(f"Quantidade de janelas criadas: {len(cotacao_feature_grouped)}")
print(f"Formato da primeira janela: {cotacao_feature_grouped[0].shape}")  # Esperado: (10, 60)

cotacao_feature_grouped[0]

Quantidade de janelas criadas: 190
Formato da primeira janela: (10, 60)

Price           Close                                                        \
Ticker       ABEV3.SA   BBSE3.SA   EGIE3.SA   EMBR3.SA   FLRY3.SA  ITSA4.SA
Date
2017-05-10  14.118645  16.562653  15.847735  15.486094  20.420807  4.513855
2017-05-11  14.368788  16.589911  15.732326  15.545165  20.508598  4.589832
2017-05-12  14.486506  16.987892  15.893902  15.564855  20.578836  4.603240
2017-05-15  14.523292  16.900669  16.009306  15.722375  20.498064  4.603240
2017-05-16  14.582152  17.249584  16.097017  15.545165  20.469973  4.589832
2017-05-17  14.449720  16.955187  15.930830  14.767414  20.315454  4.500450
2017-05-18  13.831705  15.221502  15.099895  15.161211  19.686853  4.066939
2017-05-19  13.699276  15.570421  15.418419  14.915088  20.087191  4.093756
2017-05-22  13.662491  15.428673  15.303014  15.958652  19.103903  3.977557
2017-05-23  13.897923  15.892078  15.326091  15.732218  20.333012  4.026717

Price                                               ...     Volume  \
Ticker      PETR4.SA   SUZB3.SA  TAEE4.SA USDBRL=X  ...   EGIE3.SA
Date                                                ...
2017-05-10  4.374014  17.149136  5.970147   3.1868  ...  1278375.0
2017-05-11  4.400739  17.149136  5.970147   3.1657  ...   933125.0
2017-05-12  4.587815  17.149136  5.970147   3.1390  ...  1151875.0
2017-05-15  4.656112  17.149136  5.970147   3.1777  ...   778750.0
2017-05-16  4.662052  17.149136  5.970147   3.1082  ...  1115875.0
2017-05-17  4.635325  17.149136  5.970147   3.0958  ...  1870000.0
2017-05-18  3.904840  17.149136  5.970147   3.1334  ...  3417500.0
2017-05-19  4.044404  17.149136  5.970147   3.3690  ...  2236250.0
2017-05-22  3.979076  17.149136  5.970147   3.2533  ...  1676375.0
2017-05-23  4.005800  17.149136  6.057160   3.2654  ...  1189250.0

Price                                                                         \
Ticker        EMBR3.SA   FLRY3.SA    ITSA4.SA     PETR4.SA SUZB3.SA TAEE4.SA
Date
2017-05-10   3023300.0  1165232.0  21112275.0   46271700.0      0.0    200.0
2017-05-11   1851600.0  1712429.0  18646839.0   29318000.0      0.0      0.0
2017-05-12   2602800.0   977743.0  17485227.0   83518200.0      0.0      0.0
2017-05-15   1710000.0  1654528.0  19569320.0   46914700.0      0.0      0.0
2017-05-16   3023700.0  1601081.0  37032042.0   34469300.0      0.0      0.0
2017-05-17   4583000.0   903087.0  24891664.0   30023400.0      0.0      0.0
2017-05-18  11730800.0  1138721.0  85731546.0  142924900.0      0.0      0.0
2017-05-19   4693000.0  1987936.0  47798403.0   70983900.0      0.0      0.0
2017-05-22   7361400.0  1607444.0  37490750.0   55014900.0      0.0      0.0
2017-05-23   4972700.0  1616352.0  25662930.0   48520100.0      0.0      0.0

Price
Ticker     USDBRL=X    WEGE3.SA       ^BVSP
Date
2017-05-10      0.0   5832060.0   3174100.0
2017-05-11      0.0   3423160.0   2872600.0
2017-05-12      0.0   5294640.0   3822600.0
2017-05-15      0.0   4286100.0   3290300.0
2017-05-16      0.0   7818980.0   3672400.0
2017-05-17      0.0   6475300.0   3317200.0
2017-05-18      0.0  17152980.0  11046700.0
2017-05-19      0.0  10555480.0   6120800.0
2017-05-22      0.0   7750860.0   5815800.0
2017-05-23      0.0   5398380.0   4753500.0

[10 rows x 60 columns]

In [98]:
cotacao_feature_grouped[-1]

Price         Close                                                     \
Ticker     ABEV3.SA   BBSE3.SA   EGIE3.SA   EMBR3.SA FLRY3.SA ITSA4.SA
Date
2024-12-20    12.23  36.529999  36.820000  54.959999    12.66     8.92
2024-12-23    12.22  36.490002  35.619999  55.549999    12.37     8.80
2024-12-26    12.14  36.470001  35.580002  56.240002    12.16     8.90
2024-12-27    12.07  36.279999  34.950001  56.330002    12.24     8.83

Price                                               ...     Volume             \
Ticker       PETR4.SA   SUZB3.SA TAEE4.SA USDBRL=X  ...   EGIE3.SA   EMBR3.SA
Date                                                ...
2024-12-20  35.522152  59.619999    11.34   6.1516  ...  2596800.0  9192900.0
2024-12-23  35.531796  61.240002    10.99   6.0842  ...  1641200.0  4696500.0
2024-12-26  35.770000  61.939999    11.09   6.7324  ...  1915500.0  3878300.0
2024-12-27  35.660000  61.590000    11.06   6.1485  ...  1456000.0  3926000.0

Price                                                                         \
Ticker       FLRY3.SA    ITSA4.SA    PETR4.SA    SUZB3.SA  TAEE4.SA USDBRL=X
Date
2024-12-20  2942900.0  51241000.0  59277400.0  14103300.0  225200.0      0.0
2024-12-23  1944200.0  26003600.0  43785600.0   7450600.0  338000.0      0.0
2024-12-26  1572600.0  31877700.0  22920700.0   4414200.0  223700.0      0.0
2024-12-27  2507500.0  23565700.0  24167200.0   4316400.0  210100.0      0.0

Price
Ticker        WEGE3.SA       ^BVSP
Date
2024-12-20  14233300.0  18128200.0
2024-12-23   4062300.0   9953300.0
2024-12-26   3560800.0   8338500.0
2024-12-27   3720300.0   8937000.0

[4 rows x 60 columns]

O objetivo Ã© prever o valor da aÃ§Ã£o apos 10 dias de dados temporais, com isso os dados de target sÃ£o  separados em 10 em 10 dias, diminuindo o seu tamanho para 189

In [106]:
acao= [
    "ABEV3.SA", "BBSE3.SA", "EGIE3.SA", "EMBR3.SA", "FLRY3.SA", 
    "ITSA4.SA", "PETR4.SA", "SUZB3.SA", "TAEE4.SA",
    "WEGE3.SA"
]
# Ajuste o target para garantir que ele tenha o mesmo nÃºmero de amostras que as features
# O target serÃ¡ o 'Adj Close' do dia seguinte apÃ³s cada janela de 10 dias
cotacao_target_intervalo = cotacao_target.iloc[window_size::window_size][acao].reset_index(drop=True)


print(f"Novo shape do target: {cotacao_target_intervalo.shape}")
cotacao_target_intervalo

Novo shape do target: (189, 10)

Ticker,ABEV3.SA,BBSE3.SA,EGIE3.SA,EMBR3.SA,FLRY3.SA,ITSA4.SA,PETR4.SA,SUZB3.SA,TAEE4.SA,WEGE3.SA
0,13.875853,16.257351,15.478432,16.116173,20.164452,4.026717,4.172090,17.149136,6.057160,6.421385
1,13.861135,16.208284,15.739047,15.751907,20.438370,4.042770,3.821694,17.149136,3.836201,6.476210
2,13.390269,15.619486,16.341137,15.713207,19.103903,3.921889,3.575229,17.149136,3.785723,6.089009
3,13.197028,14.910751,16.030682,15.249312,18.612259,4.020383,3.613831,17.149136,3.760486,6.092730
4,13.961534,15.537713,16.378765,15.397366,20.965130,4.118879,3.768245,17.149136,3.810963,6.615359
...,...,...,...,...,...,...,...,...,...,...
184,12.083967,34.320000,40.577805,49.150002,14.853992,10.075772,33.060886,55.732258,11.282301,56.119289
185,11.847027,34.610001,40.220821,50.549999,14.185071,10.425165,32.819839,57.620667,11.400029,56.009445
186,12.017624,33.950001,38.267292,56.900002,13.358756,9.698050,36.546833,58.782764,11.450000,53.932430
187,13.477178,35.419998,37.682224,57.320000,12.876739,9.213663,36.185261,63.363365,11.460000,55.520145
188,12.230000,36.529999,36.820000,54.959999,12.660000,8.920000,35.522152,59.619999,11.340000,55.460236

# Passando os dados para array

In [100]:
# Converta todas as janelas de DataFrame para arrays NumPy
X =[window.values for window in cotacao_feature_grouped]
X = np.array(X[:-1])

In [109]:
Y = cotacao_target_intervalo.to_numpy()

In [113]:
print(f"Shape das features de treino: {X.shape}")
print(f"Shape do target: {Y.shape}")

Shape das features de treino: (189, 10, 60)
Shape do target: (189, 10)

# Salvando features e target

In [114]:
np.save('data/feature.npy', X)
np.save('data/target.npy',Y)